import {StyleSheet, Dimensions} from 'react-native';
import colors from '../../Styles/colors';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  attendanceWrap: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#FAFAFA',
  },
  attendanceBanner: {
    backgroundColor: colors.Blue,
    height: 185,
    paddingTop: 39,
    alignItems: 'center',
  },
  backBtn: {
    alignSelf: 'flex-start',
    marginLeft: 20,
    top: -10,
    position: 'relative',
  },
  bannerHeading: {
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
    color: colors.White,
  },
  punchAttendanceWrap: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    marginTop: -90,
    paddingHorizontal: 14,
    paddingVertical: 22,
    height: '88%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 5,
  },
  punchAttendanceHead: {
    justifyContent: 'center',
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderColor: colors.HafWhite,
    paddingBottom: 14,
    width: '100%',
  },
  punchAttendanceHeading: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    color: colors.Black,
  },
  punchInWrap: {
    marginTop: 50,
    justifyContent: 'center',
    alignSelf: 'center',
    borderBottomWidth: 2,
    borderColor: colors.HafWhite,
    width: '70%',
    flexDirection: 'column',
    alignItems: 'center',
    paddingBottom: 20,
  },
  punchIn: {
    width: 116,
    height: 116,
    backgroundColor: colors.Blue,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 100,
  },
  punchInText: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    color: colors.White,
  },
  punchInDate: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    color: colors.Black,
    marginTop: 10,
  },
  punchOutWrap: {
    marginTop: 50,
    justifyContent: 'center',
    alignSelf: 'center',
    width: '70%',
    flexDirection: 'column',
    alignItems: 'center',
    paddingBottom: 20,
  },
  punchOut: {
    width: 116,
    height: 116,
    backgroundColor: '#DADADA',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 100,
  },
  punchOutText: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    color: colors.Black,
  },
  bigBlue: {
    color: 'blue',
    fontWeight: 'bold',
    fontSize: 30,
    alignSelf: 'center',
    // backgroundColor:colors.Grey,
    // borderRadius:50,

    top: 40,
  },
  map: {
    height: 400,
    width: 100,
  },
  locationText: {
    fontWeight: 'bold',
    marginLeft: 30,
    // color:colors.White,
  },
  position: {
    color: colors.Black,
  },
});
export default styles;
