import {StyleSheet, Dimensions} from 'react-native';
import colors from '../../Styles/colors';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  myworkWrap: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#FAFAFA',
    top: -60,
    overflow: 'hidden',
  },

  attendenceCorrectionBanner: {
    backgroundColor: colors.Blue,
    height: 185,
    paddingTop: 9,
    alignItems: 'center',
    overflow: 'hidden',
  },
  backBtn: {
    alignSelf: 'flex-start',
    marginLeft: 20,
    top: -10,
    position: 'relative',
  },
  bannerHeading: {
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
    color: colors.White,
  },
  heading: {
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
    color: colors.White,
  },
  attendenceCorrectionWrapInner: {
    width: 335,
    backgroundColor: colors.White,
    borderRadius: 12,
    marginTop: -130,
    paddingHorizontal: 14,
    paddingVertical: 22,
    alignSelf: 'center',
    minHeight: 500,
  },
  profileWrap: {
    width: 304,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    shadowColor: '#0000000A',
    shadowOffset: '12',
    shadowOpacity: 100,
    paddingHorizontal: 14,
    paddingVertical: 22,
    marginBottom: 10,
    display: 'flex',
  },
  profile: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
  },

  profileText: {
    marginLeft: 10,
  },
  profileName: {
    fontSize: 16,
    lineHeight: 25,
    fontWeight: 'bold',
    color: colors.Blue,
  },
  profileJob: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
    color: '#C9C9C9',
  },
  timeBoxWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  timeList: {
    width: '33%',
  },
  typeText: {
    textAlign: 'center',
  },
  timeLists: {
    width: '40%',
    marginRight: 30,
    // marginTop: -20,
  },
  dropdown: {
    width: '100%',
    // height: '50%',
    backgroundColor: colors.White,
    fontFamily: 500,
    elevation: 2,
    // color: colors.Blue,
    // shadowOpacity: 0.15,
    // shadowRadius: 3.84,
    // elevation: 5,'
    marginTop: -15,
  },
  textdrop: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.Black,
  },

  timeLabel: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.Black,
  },
  timeDigit: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: '#8B9390',
    maxWidth: 70,
    width: 70,
    overflow: 'hidden',
  },
  btnList: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 28,
  },
  approved: {
    width: 108,
    height: 28,
    backgroundColor: colors.Blue,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginRight: 10,
  },
  approvedBtn: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: colors.White,
  },
  Edit: {
    width: 108,
    height: 28,
    backgroundColor: colors.White,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginTop: 32,
    // marginRight: 15,
    // marginLeft: 60,
    borderColor: colors.Blue,
    borderWidth: 1,
  },
  Edits: {
    width: 108,
    height: 28,
    backgroundColor: colors.White,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginTop: 32,
    // marginRight: 15,
    marginLeft: 60,
    borderColor: colors.Blue,
    borderWidth: 1,
  },
  rejectBtn: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: colors.Blue,
  },
  rejectBtnBg: {
    backgroundColor: colors.Red,
    color: colors.White,
    width: 108,
    height: 28,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginTop: 32,
    borderColor: colors.Red,
    borderWidth: 1,
  },
  statusbtn: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: colors.Blue,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
});
export default styles;
