import {StyleSheet, Dimensions} from 'react-native';
import colors from '../../Styles/colors';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  dashboardWrap: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#FAFAFA',
  },
  dashboardBanner: {
    backgroundColor: colors.Blue,
    height: 185,
    paddingTop: 39,
    alignItems: 'center',
  },
  backBtn: {
    alignSelf: 'flex-start',
    marginLeft: 20,
    top: -10,
    position: 'relative',
  },
  bannerHeading: {
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
    color: colors.White,
  },
  detailWrap: {
    marginTop: -90,
    marginBottom: 20,
  },
  detailInner: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 22,
    marginBottom: 20,
    shadowColor: '#0000000A',
    shadowOffset: '12',
    shadowOpacity: 100,
  },
  detailHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
  },
  leftLable: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.Black,
  },
  rightLabel: {
    fontSize: 10,
    lineHeight: 18,
    fontWeight: '400',
    color: '#8B9390',
  },
  itemLeftLable: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.Blue,
  },
  graphInfo: {
    flexDirection: 'column',
    marginBottom: 15,
  },
  graphImg: {
    height: 270,
  },
  detailAttendanceList: {
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  detailAttendanceItem: {
    width: '33%',
    height: 74,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 22,
    marginBottom: 20,
    shadowColor: '#0000000A',
    shadowOffset: '12',
    shadowOpacity: 100,
  },
  btnList: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 10,
    width: 335,
    alignSelf: 'center',
  },
  edit: {
    width: '50%',
    height: 50,
    backgroundColor: colors.Blue,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginRight: 10,
  },
  editBtn: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: colors.White,
  },
  delete: {
    width: '50%',
    height: 50,
    backgroundColor: colors.White,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginRight: 10,
    borderColor: colors.Blue,
    borderWidth: 1,
  },
  deleteBtn: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: colors.Blue,
  },

  profileDesList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 15,
  },
  desListLabel: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
    color: '#C9C9C9',
  },
  desListLabelRight: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
    color: '#000',
  },
  categoryWrap: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    marginTop: 20,
    paddingHorizontal: 14,
    paddingVertical: 22,
  },
  categoryHeading: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '700',
    color: colors.Black,
  },
  categoryDes: {},
  categoryList: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingTop: 15,
    alignItems: 'center',
  },
  categoryListImg: {
    marginRight: 20,
  },
  categoryListLabel: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '500',
    color: colors.Black,
  },
  timeBoxWrap: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    marginTop: 20,
    paddingHorizontal: 14,
    paddingVertical: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timeList: {
    alignItems: 'center',
    width: '33%',
  },
  timeListBorder: {
    alignItems: 'center',
    borderColor: '#ccc',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    width: '33%',
  },
  timeLabel: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    color: '#8B9390',
  },
  timeDigit: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.Black,
  },
});
export default styles;
