import {StyleSheet, Dimensions} from 'react-native';
import colors from '../../Styles/colors';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  leaveWrap: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#FAFAFA',
  },
  leaveBanner: {
    backgroundColor: colors.Blue,
    height: 185,
    paddingTop: 39,
    alignItems: 'center',
  },
  backBtn: {
    alignSelf: 'flex-start',
    marginLeft: 20,
    top: -10,
    position: 'relative',
  },
  bannersHeading: {
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '700',
    color: colors.White,
    top: 30,
  },
  timeBoxWrap: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    marginTop: -90,
    paddingHorizontal: 14,
    paddingVertical: 22,
  },
  calenderWrap: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 22,
  },
  calenderForm: {
    marginBottom: 20,
  },
  calenderFormLabel: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
    color: '#C1C7D0',
    marginBottom: 10,
  },
  calenderFormInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    paddingBottom: 15,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '400',
  },
  calenderFormBtn: {
    alignSelf: 'center',
    width: '80%',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    backgroundColor: colors.Blue,
  },
  formBtnText: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '500',
    color: colors.White,
  },

  timeBox: {
    backgroundColor: colors.Blue,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 22,
  },
  dwonBtnImgs: {
    width: 16,
    height: 16,
    marginRight: 10,
    marginTop: 10,
  },
  timeList: {
    alignItems: 'center',
    width: '33%',
  },
  timeListBorder: {
    alignItems: 'center',
    borderColor: '#6BA6FF',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    width: '33%',
  },
  timeLabel: {
    fontSize: 24,
    lineHeight: 35,
    fontWeight: '400',
    color: '#6BA6FF',
  },
  timeDigit: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.White,
  },
  buttonListWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 335,
    alignSelf: 'center',
    marginTop: 20,
  },
  annualBtn: {
    width: 117,
    height: 62,
    borderRadius: 12,
    borderColor: '#ccc',
    borderWidth: 1,
    paddingLeft: 12,
    justifyContent: 'center',
    marginRight: 5,
  },
  annualBtnSelected: {
    width: 117,
    height: 62,
    borderRadius: 12,
    borderColor: '#ccc',
    borderWidth: 1,
    paddingLeft: 12,
    justifyContent: 'center',
    marginRight: 5,
    backgroundColor: colors.Blue,
  },
  calenderWrap: {
    width: 335,
    alignSelf: 'center',
    backgroundColor: colors.White,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 22,
    marginTop: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 5,
  },
  calenderForm: {
    marginBottom: 20,
    borderBottomWidth: 1,
  },
  inputview: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    borderBottomWidth: 1,
  },
  calenderFormLabel: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
    color: '#C1C7D0',
    marginBottom: 10,
  },
  calenderFormInput: {
    borderBottomColor: '#ccc',
    paddingBottom: 15,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '400',
    flex: 1,
    // position:"relative"
  },
  calenderFormBtn: {
    alignSelf: 'center',
    width: '80%',
    borderRadius: 25,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 40,
    backgroundColor: colors.Blue,
  },
  formBtnText: {
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '500',
    color: colors.White,
  },
  dropdown: {
    width: '100%',
    backgroundColor: colors.White,
    borderRadius: 12,
    marginTop: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3.84,
    elevation: 5,
  },
  bannerHeading: {
    width: 128,
    height: 30,
    backgroundColor: colors.White,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginRight: 10,
  },
  tabtext: {
    color: colors.Black,
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '500',
  },

  tabbtn: {
    display: 'flex',
    flexDirection: 'row',
  },
  selectedBannerHeading: {
    width: 128,
    height: 30,
    backgroundColor: '#32ADFC',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 25,
    marginRight: 10,
  },
});
export default styles;
